# Copyright (c) 2020, NVIDIA CORPORATION. All rights reserved.
#
# NVIDIA CORPORATION and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto. Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA CORPORATION is strictly prohibited.

# The robot description file defines the generalized coordinates and how to map
# those to the underlying URDF DOFs.

api_version: 1.0

# Defines the generalized coordinates. Each generalized coordinate is assumed
# to have an entry in the URDF, except when otherwise specified below under
# cspace_urdf_bridge.
cspace:
  - shoulder_pan_joint
  - shoulder_lift_joint
  - elbow_joint
  - wrist_1_joint
  - wrist_2_joint
  - wrist_3_joint

root_link: world

default_q: [-1.57, -1.57, -1.57, -1.57, 1.57, 0]

# Most dimensions of the cspace have a direct corresponding element
# in the URDF. This list of rules defines how unspecified coordinates
# should be extracted.
cspace_to_urdf_rules:
  # Example:
  # - {name: robot_finger_joint1, rule: fixed, value: 0.025}

composite_task_spaces: []


collision_spheres:
    - base_link:
        - center: [0.0, 0.0, 0.015]
          radius: 0.07
        - center: [0.0, 0.0, 0.085]
          radius: 0.06
    - shoulder_link: 
        - center: [0.0, 0.0, 0.005]
          radius: 0.07
        - center: [0.0, -0.06, 0.0]
          radius: 0.05
        - center: [0.0, -0.12, 0.01]
          radius: 0.07
    - upper_arm_link:
        - center: [-0.078, 0.0, 0.12]
          radius: 0.05
        - center: [-0.149, 0.0, 0.12]
          radius: 0.05
        - center: [-0.235, 0.0, 0.12]
          radius: 0.07
    - forearm_link:
        - center: [-0.0, 0.0, 0.029]
          radius: 0.06
        - center: [-0.075, 0.0, 0.029]
          radius: 0.05
        - center: [-0.15, 0.0, 0.029]
          radius: 0.05
        - center: [-0.215, 0.0, 0.029]
          radius: 0.06
    - wrist_1_link:
        - center: [0.0, 0.0, 0.0]
          radius: 0.06
    -  wrist_2_link:
        - center: [0.0, 0.0, 0.0]
          radius: 0.06
    -  wrist_3_link:
        - center: [0.0, 0.0, 0.0]
          radius: 0.06

